apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "leadicaldev-132e"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "leadicaldev-132e"
    spec:
      containers:
        - name: "leadicaldev-132e"
          image: "leadicalazreg.azurecr.io/leadicaldev"
          ports:
          - containerPort: 80